name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install sdl2
      run: sudo apt-get install -y libsdl2-dev
    - name: Install sdl2-ttf
      run: sudo apt-get install -y libsdl2-ttf-dev
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
