name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install sdl2
      run: sudo apt-get install -y libsdl2-dev
<<<<<<< HEAD
    - name: Install sdl2-ttf
=======
>>>>>>> 2566c9bf7371b416b6a2e3feb28193cfb775f1f4
      run: sudo apt-get install -y libsdl2-ttf-dev
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
